# Generated by Django 5.2.5 on 2025-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='last time the device was online'),
        ),
    ]
