from rest_framework import serializers
from .models import Device


class DeviceSerializer(serializers.ModelSerializer):
    class Meta:
        model = Device
        fields = ['id', 'name', 'is_online', 'last_seen']
        # 'id' and 'last_seen' are set to read_only because they are autogenerated
        read_only_fields = ['id', 'last_seen']

# Used during PATCH so 'name' and 'is_online' can be updated
class DeviceUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Device
        fields = ['name', 'is_online']
        
